apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: test-ns
spec:
  containers:
    - name: curl-container
      image: curlimages/curl
      command: ["sleep", "infinity"]

